# Generated by Django 2.2.1 on 2019-06-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
        ),
    ]
