# Generated by Django 2.2.1 on 2019-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190602_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover_image',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
